#------------------------------------------------------------------------------
# en: Threading Configuration | ru: Конфигурация потоков
#------------------------------------------------------------------------------
# en: Controls parallel execution capacity (min: 1) | ru: Управление количеством параллельных выполнений (минимум: 1)
threads: 1

#------------------------------------------------------------------------------
# en: Timing Settings | ru: Настройки времени
#------------------------------------------------------------------------------
# en: Initial delay range before starting operations (seconds) | ru: Диапазон начальной задержки перед началом выполнения (секунды)
delay_before_start:
    min: 10
    max: 15

# en: Delay between tasks (seconds) | ru: Задержка между задачами (секунды)
delay_between_tasks:
    min: 100
    max: 300

# TELEGRAM DATA
send_stats_to_telegram: true

tg_token: ""  # https://t.me/BotFather
tg_id: ""  # https://t.me/getmyid_bot

#------------------------------------------------------------------------------
# Network Settings
#------------------------------------------------------------------------------

# EXPchain Testnet RPC endpoint
expchain_rpc: https://rpc1-testnet.expchain.ai
# EXPchain Testnet Explorer
expchain_explorer: https://blockscout-testnet.expchain.ai/

# Sepolia Testnet RPC endpoint
sepolia_rpc: https://ethereum-sepolia-rpc.publicnode.com
# Sepolia Testnet Explorer
sepolia_explorer: https://sepolia.etherscan.io

# BSC Testnet RPC endpoint
bsc_rpc: https://bsc-testnet-rpc.publicnode.com
# BSC Testnet Explorer
bsc_explorer: https://testnet.bscscan.com